const DIGITAL_FLUENCY_DURATION = 60;
const SPATIAL_ORIENTATION_DURATION = 60;
const WORDS_MEMORY_DURATION = 60;

export {
  DIGITAL_FLUENCY_DURATION,
  SPATIAL_ORIENTATION_DURATION,
  WORDS_MEMORY_DURATION,
};
